python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 2 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000
python train_sdf_depth.py -s /mnt/workfiles/datasets/dtu/scan24 -m outputs/loop/scan24 -r 8 --eval --lambda_distortion 1000